// <auto-generated />
using FeuerSoftware.MailAgent.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FeuerSoftware.MailAgent.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.6");

            modelBuilder.Entity("FeuerSoftware.MailAgent.Data.AdditionalPatternEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Pattern")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PatternSettingsId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PatternSettingsId");

                    b.ToTable("AdditionalPatterns");
                });

            modelBuilder.Entity("FeuerSoftware.MailAgent.Data.EmailAccountEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ApiKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("AuthenticationType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EMailHost")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EMailPassword")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("EMailPort")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EMailSenderFilter")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EMailSubjectFilter")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EMailUsername")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("EmailAccounts");
                });

            modelBuilder.Entity("FeuerSoftware.MailAgent.Data.MailAgentSettingsEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("DisableEmailAgeThreshold")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EMailMode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("EMailPollingIntervalSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<string>("HeartbeatInterval")
                        .HasColumnType("TEXT");

                    b.Property<string>("HeartbeatUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IgnoreCertificateErrors")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OutputPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ProcessMode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SecretKeyPassphrase")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("MailAgentSettings");
                });

            modelBuilder.Entity("FeuerSoftware.MailAgent.Data.PatternSettingsEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CityPattern")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DistrictPattern")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FactsPattern")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("HouseNumberPattern")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("KeywordPattern")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LatitudePattern")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LongitudePattern")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NumberPattern")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ReporterNamePattern")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ReporterPhonePattern")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RicPattern")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("StartPattern")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("StreetPattern")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ZipCodePattern")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("PatternSettings");
                });

            modelBuilder.Entity("FeuerSoftware.MailAgent.Data.AdditionalPatternEntity", b =>
                {
                    b.HasOne("FeuerSoftware.MailAgent.Data.PatternSettingsEntity", null)
                        .WithMany("AdditionalProperties")
                        .HasForeignKey("PatternSettingsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FeuerSoftware.MailAgent.Data.PatternSettingsEntity", b =>
                {
                    b.Navigation("AdditionalProperties");
                });
#pragma warning restore 612, 618
        }
    }
}
