name: PR Test & License

on:
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  build-test-license:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'
      - name: Cache NuGet packages
        uses: actions/cache@v4
        with:
          path: ~/.nuget/packages
          key: pr-nuget-${{ runner.os }}-${{ hashFiles('**/packages.lock.json') }}-${{ hashFiles('**/*.csproj') }}
          restore-keys: |
            pr-nuget-${{ runner.os }}-
      - name: Restore
        run: dotnet restore MailAgent.sln
      - name: Build (Debug)
        run: dotnet build MailAgent.sln -c Debug --no-restore
      - name: Run tests
        run: dotnet test MailAgent.Tests/MailAgent.Tests.csproj -c Debug --no-build --logger "trx;LogFileName=test-results.trx" --results-directory test-results
      - name: Collect licenses
        uses: ./.github/actions/collect-licenses
        with:
          project: MailAgent/MailAgent.csproj
          output-file: licenses.md
      - name: Upload artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: pr-artifacts
          path: |
            test-results
            licenses.md
